Repository soft-nougat/sogeti_qaif, pull requests merged in 2021-09, with the labels that each got.

#12 nbdt open() bug
  examples.py
Labels: bug

#13 remove open() nbdt
  examples.py
Labels: bug, enhancement

#14 fix some bugs
  examples.py
  requirements.txt
Labels: bug

#15 Change numpy requirement
  requirements.txt
Labels: bug

#17 Feature/xai example
  __pycache__/examples.cpython-38.pyc
  examples.py
  requirements.txt
Labels: enhancement

#19 keras bug fix
  examples.py
  requirements.txt
Labels: bug

#20 Update tabular bias
  __pycache__/examples.cpython-38.pyc
  examples.py
  examples_data/titanic.csv
  examples_data/titanic_cleaned.csv
Labels: bug, enhancement

#22 update keras 2.2.5
  requirements.txt
Labels: bug

#23 Add gitignore and cleanup cache files/folders
  .gitignore
  .ipynb_checkpoints/Untitled-checkpoint.ipynb
  __pycache__/business_understanding.cpython-38.pyc
  __pycache__/examples.cpython-38.pyc
  __pycache__/helper.cpython-38.pyc
  __pycache__/principles.cpython-38.pyc
Labels: cleanup

#24 Update documentation
  README.md
Labels: documentation

#26 Revert "Move rendering functions"
  examples.py
  helper.py
  qaif_app.py
  render.py
  requirements.txt
Labels: bug

#27 Refactor steps without Streamlit version upgrade
  qaif_app.py
  render.py
Labels: cleanup

#30 Feature/data version control
  .dvc/.gitignore
  .dvc/config
  .dvc/plots/confusion.json
  .dvc/plots/confusion_normalized.json
  .dvc/plots/default.json
  .dvc/plots/linear.json
  .dvc/plots/scatter.json
  .dvc/plots/smooth.json
  .dvcignore
  examples.py
Labels: enhancement

#31 Feature/data version control
  .dvc/.gitignore
  .dvc/config
  .dvc/plots/confusion.json
  .dvc/plots/confusion_normalized.json
  .dvc/plots/default.json
  .dvc/plots/linear.json
  .dvc/plots/scatter.json
  .dvc/plots/smooth.json
  .dvcignore
  examples.py
  render.py
Labels: enhancement

#32 add the rest of the dvc calls
  examples.py
Labels: enhancement
